image: node:14

stages:
  - build
  - test

frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

frontend_test:
  stage: test
  script:
    - cd frontend
    - npm test
