image: node:14

stages:
  - build
  - test

frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build

frontend_test:
  stage: test
  script:
    - cd frontend
    - CI-true npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
