image: node:14

stages:
  - build
  - test

cache:
  paths:
    - backend/node_modules/

backend_build:
  stage: build
  script:
    - cd backend
    - npm install

backend_test:
  stage: test
  script:
    - cd backend
    - npm test

  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
